package com.fabioqmarsiaj.order.domain;

import com.fabioqmarsiaj.order.domain.event.OrderCancelled;
import com.fabioqmarsiaj.order.domain.event.OrderCompleted;
import com.fabioqmarsiaj.order.domain.event.OrderCreated;
import com.fabioqmarsiaj.order.domain.event.OrderDomainEvent;
import com.fabioqmarsiaj.order.domain.event.OrderFailed;
import com.fabioqmarsiaj.order.domain.event.PaymentApproved;
import com.fabioqmarsiaj.order.domain.event.PaymentDeclined;
import com.fabioqmarsiaj.order.domain.event.ShipmentCreated;
import com.fabioqmarsiaj.order.domain.event.ShipmentFailed;
import com.fabioqmarsiaj.order.domain.event.StockRejected;
import com.fabioqmarsiaj.order.domain.event.StockReserved;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * The {@code Order} aggregate root, implemented using the Event Sourcing
 * pattern.
 *
 * <p>Two kinds of operations exist on this class:
 * <ul>
 *   <li><b>Commands</b> (e.g. {@link #create}, {@link #markStockReserved}) —
 *       public methods that validate business rules given the current state,
 *       and if valid, raise a new domain event.</li>
 *   <li><b>Apply</b> ({@link #apply(OrderDomainEvent)}) — the single place
 *       where domain events actually mutate the aggregate's fields. This
 *       method must be a pure function of (current state, event) -> new
 *       state, with no validation and no side effects, because it is also
 *       used to rebuild an aggregate purely by replaying its historical
 *       events ({@link #rehydrate}).</li>
 * </ul>
 *
 * <p>The separation matters: {@code raise()} both applies the event
 * (updating in-memory state immediately) AND records it as "pending" so the
 * application layer can persist it afterwards. {@code rehydrate()} only
 * calls {@code apply()} directly for each historical event, without
 * re-recording them as pending (they're already persisted).
 */
public class Order {

    private UUID id;
    private OrderStatus status;
    private String customerId;
    private List<OrderLineItem> items;
    private long totalAmountCents;

    /**
     * Events raised by command methods since this instance was created or
     * rehydrated, not yet persisted. The application layer is responsible
     * for reading these via {@link #pullPendingEvents()} and persisting
     * them to the event store + outbox in the same transaction.
     */
    private final List<OrderDomainEvent> pendingEvents = new ArrayList<>();

    /**
     * Private constructor: instances must be created via {@link #create}
     * (new order) or {@link #rehydrate} (reconstructing from history).
     */
    private Order() {
    }

    // ---------------------------------------------------------------
    // Commands
    // ---------------------------------------------------------------

    /**
     * Creates a brand-new order and raises the initial {@link OrderCreated}
     * event.
     *
     * @param orderId    the id to assign to the new order (generated by the
     *                   caller so it's known before persistence)
     * @param customerId the customer placing the order
     * @param items      the line items being ordered
     * @return a new {@code Order} instance with one pending event
     */
    public static Order create(UUID orderId, String customerId, List<OrderLineItem> items) {
        // TODO:
        //  1. Validate inputs (e.g. items must not be empty).
        //  2. Compute totalAmountCents from the items.
        //  3. Instantiate an Order, then raise() an OrderCreated event with
        //     a freshly generated eventId and Instant.now().
        //  4. Return the order.
        throw new UnsupportedOperationException("not implemented yet");
    }

    /**
     * Command: react to inventory-service confirming stock reservation.
     * Only valid while the order is in {@link OrderStatus#CREATED}.
     */
    public void markStockReserved() {
        // TODO: validate current status, then raise(new StockReserved(...)).
        throw new UnsupportedOperationException("not implemented yet");
    }

    /**
     * Command: react to inventory-service rejecting stock reservation.
     * This is a compensation trigger — the order moves straight to
     * {@link OrderStatus#CANCELLED}.
     */
    public void markStockRejected(String reason) {
        // TODO: validate current status, then raise(new StockRejected(...))
        //  followed by raise(new OrderCancelled(...)).
        throw new UnsupportedOperationException("not implemented yet");
    }

    /**
     * Command: react to payment-service approving payment. Only valid while
     * the order is in {@link OrderStatus#STOCK_RESERVED}.
     */
    public void markPaymentApproved(String paymentId) {
        // TODO: validate current status, then raise(new PaymentApproved(...)).
        throw new UnsupportedOperationException("not implemented yet");
    }

    /**
     * Command: react to payment-service declining payment. This is a
     * compensation trigger — the order moves to {@link OrderStatus#CANCELLED}
     * (the caller / application service is responsible for issuing a
     * ReleaseStockCommand as part of the same reaction).
     */
    public void markPaymentDeclined(String reason) {
        // TODO: validate current status, then raise(new PaymentDeclined(...))
        //  followed by raise(new OrderCancelled(...)).
        throw new UnsupportedOperationException("not implemented yet");
    }

    /**
     * Command: react to shipping-service confirming shipment creation. This
     * is the happy-path terminal transition: STOCK not enough, must also
     * have had payment approved beforehand.
     */
    public void markShipmentCreated(String shipmentId) {
        // TODO: validate current status, then raise(new ShipmentCreated(...))
        //  followed by raise(new OrderCompleted(...)).
        throw new UnsupportedOperationException("not implemented yet");
    }

    /**
     * Command: react to shipping-service failing to create a shipment. This
     * is the final compensation trigger — the order moves to
     * {@link OrderStatus#FAILED} (the caller / application service is
     * responsible for issuing RefundPaymentCommand + ReleaseStockCommand).
     */
    public void markShipmentFailed(String reason) {
        // TODO: validate current status, then raise(new ShipmentFailed(...))
        //  followed by raise(new OrderFailed(...)).
        throw new UnsupportedOperationException("not implemented yet");
    }

    // ---------------------------------------------------------------
    // Event sourcing mechanics
    // ---------------------------------------------------------------

    /**
     * Rebuilds an {@code Order} purely by replaying its historical events,
     * in the order they occurred. No validation happens here — history is
     * assumed to be valid because it was already validated (via
     * {@code raise()}) at the time each event was originally recorded.
     *
     * @param history the full, ordered list of events for one order,
     *                as read from the event store
     * @return the order in its current state
     */
    public static Order rehydrate(List<OrderDomainEvent> history) {
        // TODO:
        //  1. Guard against an empty history (should never happen).
        //  2. Create an empty Order instance.
        //  3. For each event in history, call apply(event) directly
        //     (do NOT call raise() — these events are already persisted,
        //     we must not re-add them to pendingEvents).
        //  4. Return the order.
        throw new UnsupportedOperationException("not implemented yet");
    }

    /**
     * Applies a domain event to this aggregate's in-memory state and also
     * records it as pending (to be persisted by the application layer).
     * Used exclusively by command methods.
     */
    private void raise(OrderDomainEvent event) {
        apply(event);
        pendingEvents.add(event);
    }

    /**
     * The single source of truth for how each event type mutates aggregate
     * state. Implement this using an exhaustive Java 21 pattern-matching
     * {@code switch} over the sealed {@link OrderDomainEvent} interface —
     * the compiler will error if a new event type is added to the sealed
     * interface but not handled here.
     *
     * <p>This method must have NO side effects beyond mutating {@code this}
     * (no validation, no exceptions for "invalid" states, no I/O) since it
     * is reused by both {@link #raise} and {@link #rehydrate}.
     */
    private void apply(OrderDomainEvent event) {
        // TODO: implement with a pattern-matching switch, e.g.:
        //
        // switch (event) {
        //     case OrderCreated e -> {
        //         this.id = e.orderId();
        //         this.customerId = e.customerId();
        //         this.items = e.items();
        //         this.totalAmountCents = e.totalAmountCents();
        //         this.status = OrderStatus.CREATED;
        //     }
        //     case StockReserved e -> this.status = OrderStatus.STOCK_RESERVED;
        //     case StockRejected e -> { /* no field change beyond status, handled by OrderCancelled */ }
        //     case PaymentApproved e -> this.status = OrderStatus.PAYMENT_APPROVED;
        //     case PaymentDeclined e -> { /* no field change beyond status, handled by OrderCancelled */ }
        //     case ShipmentCreated e -> this.status = OrderStatus.SHIPPED;
        //     case ShipmentFailed e -> { /* no field change beyond status, handled by OrderFailed */ }
        //     case OrderCancelled e -> this.status = OrderStatus.CANCELLED;
        //     case OrderCompleted e -> this.status = OrderStatus.COMPLETED;
        //     case OrderFailed e -> this.status = OrderStatus.FAILED;
        // }
        //
        // Fill in the real logic below (the sketch above is a starting
        // point, not the final answer — double check status transitions
        // against the OrderStatus javadoc diagram).
        throw new UnsupportedOperationException("not implemented yet");
    }

    /**
     * Returns and clears the list of events raised since this instance was
     * created/rehydrated. The application layer calls this right before
     * persisting, to know exactly what needs to be written to the event
     * store + outbox.
     */
    public List<OrderDomainEvent> pullPendingEvents() {
        // TODO: copy pendingEvents to a new unmodifiable list, clear the
        //  internal list, and return the copy.
        throw new UnsupportedOperationException("not implemented yet");
    }

    // ---------------------------------------------------------------
    // Getters
    // ---------------------------------------------------------------

    public UUID getId() {
        return id;
    }

    public OrderStatus getStatus() {
        return status;
    }

    public String getCustomerId() {
        return customerId;
    }

    public List<OrderLineItem> getItems() {
        return items;
    }

    public long getTotalAmountCents() {
        return totalAmountCents;
    }
}
